[workspace]
resolver = "2"

members = [
    "abi",
    "apiserver",
    "hello-rocket", "hello-actixweb", "hello-axum", "hello-diesel", "hello-sqlite3", "hello-jwt",
    "repository",
    "service"
]
